#!/bin/bash

MEM_OPTS="-Xms2g -Xmx2g -XX:MaxDirectMemorySize=4g"
GC_OPTS=" -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB"

# Extra options to be passed to the jvm
NETTY_OPTS=" -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.maxCapacity.default=1000 -Dio.netty.recycler.linkCapacity=1024"
CLASSPATH=$(find /pulsar/lib/ /pulsar/offloaders -name *.jar | grep -v presto | grep -v 'logging.log4j-log4j-slf4j-impl-2.10.0.jar' | tr '\n' ':' | sed 's/:$//'):/pulsar/instances/java-instance.jar:$EXTRA_CLASSPATH

JAVA=$(which java)

CMD=$(cat<<EOF
  $(which java) \
  -Dpulsar.functions.java.instance.jar=/pulsar/instances/java-instance.jar \
  -Dpulsar.functions.python.instance.file=/pulsar/instances/python-instance/python_instance_main.py \
  -Dpulsar.functions.extra.dependencies.dir=/instances/deps \
  -Dlog4j.configurationFile=/conf/log4j.properties \
  -Djute.maxbuffer=10485760 \
  -Djava.net.preferIPv4Stack=true \
  -javaagent:/pulsar/lib/org.aspectj-aspectjweaver-1.9.2.jar \
  -Dio.netty.leakDetectionLevel=disabled \
  -Dio.netty.recycler.maxCapacity.default=1000 \
  -Dio.netty.recycler.linkCapacity=1024" \
  $MEM_OPTS \
  $GC_OPTS \
  $NETTY_OPTS \
  -cp ${CLASSPATH} \
  ${EXPTRA_OPTS}
EOF
)

${CMD} org.apache.pulsar.PulsarClusterMetadataSetup \
  --cluster pulsar \
  --zookeeper $(grep zookeeperServers /conf/pulsar.conf | grep -v '#' | cut -d'=' -f2) \
  --configuration-store $(grep configurationStore /conf/pulsar.conf | grep -v '#'| cut -d'=' -f2 | cut -d',' -f1) \
  --web-service-url http://localhost:8080 \
  --web-service-url-tls https://localhost:8443 \
  --broker-service-url pulsar://localhost:6650 \
  --broker-service-url-tls pulsar+ssl://localhost:6651

$CMD org.apache.pulsar.PulsarBrokerStarter --broker-conf /conf/pulsar.conf $@
